name: Custom-github actions

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Failure-alert:
    name: Failure-email-alert
    runs-on: ubuntu-latest
    needs: [super-lint]
    if: failure()
    env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
    steps:
      - name: Send email on failure
        uses: kantakumari/custom-actions-2@v1.1.4
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          username: ${{ env.USER_EMAIL }}
          password: ${{ env.USER_PASSWORD }} 
      
    
