name: Github actions

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Failure-alert:
    name: Send email on failure
    runs-on: ubuntu-latest
    needs: [super-lint]
    if: failure()
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: kantakumari/custom-github-actions@v3
        with:
          python-version: 3.x
      - name: Run email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}  
          run: echo "failed sent"
