name: Github actions

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name:  Run email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: python sendmail.py "${{ github.job }}" "${{ github.repository }}" "${{ github.workflow }}"
  
