name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo Hello, world!

      - name: Send email notification 
        if: always()
        uses: dawidd6/action-send-mail@v2
        with: 
          # mail server settings
          server_address: stmp.gmail.com
          sever_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          #email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status}}
          #email body
          body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has {{ job.status }}
          to: kanta@iiitmanipur.ac.in
          from: Kanta Kumari